### ISSUE TITLE
Right click to edit macro keys doesn't work

### ISSUE THREAD

**Issue by jgarvin** [captdeaf/keybard#19]
It just pops up the chrome context menu.

**Comment by captdeaf** [comment]
Two things I can think of:

1) Under Menu->Dev options, there's an option to disable r-click events. Is this enabled?

2) Any chance you have an extension that blocks r-click events from being captured? I know there's at least a few out there that do so, since some websites try to prevent inspect/see image/etc etc.

**Comment by binduwavell** [comment]
While I don't have the browser context menu popup, often the menu opens and closes when I release the mouse button. I often have to right click several times to get the menu go stay open.

**Comment by captdeaf** [comment]
There was a weird issue (browser weirdness) with the context menus if RMB was held too long (300ms). Should be fixed now, if you can test on https://captdeaf.github.io/keybard/

**Comment by jgarvin** [comment]
First try testing without changing any extensions, I now get the menu (better!), but the chrome context menu would also appeared over it. Checked my extensions and I specifically have an extension for enabling right click on sites that disable it, whoops. So assume it was a combo of the 300ms bug and that.
